### ISSUE TITLE
Hacer la dependencia Typescript friendly

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-web-tools#2]
Hay que incluir un archivo `index.d.ts` en el build

**Comment by fdodino** [comment]
después de ejecutar un `npm run build` veo que ya lo tenemos

![image](https://github.com/user-attachments/assets/83fee1be-f041-4cd0-ab5f-58cbbdd765ef)

Cierro el issue @PalumboN a menos de que falte hacer algo más.
