### ISSUE TITLE
Exponer la Evaluation para usarla desde afuera

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-web-tools#3]
Así por ejemplo se pueden mandar mensajes a objetos o _queriarla_ para usarla en otras herramientas.

Principalmente pensando en la interacción con un **REPL** y el **diagrama dinámico**.

**Comment by fdodino** [comment]
Esto no es algo de wollok-ts @PalumboN ?

**Comment by PalumboN** [comment]
No, decía principalmente exponer al interpreter en la API de (lo que ahora es) `LocalGame`:
https://github.com/uqbar-project/wollok-web-tools/blob/950094e6e57f6d1dfd0e04f03537107178c3c28b/src/game/game.ts#L35

Dado que el REPL y el Diagrama ya fueron implementados usando este proyecto, voy a cerrar issue 🚀
