### ISSUE TITLE
Quitar elementos de una lista con `remove` desincroniza los índices en el diagrama de objetos

### ISSUE THREAD

**Issue by julian-berbel** [uqbar-project/wollok-web-tools#8]
Video reproduciendo el issue:

[Screencast from 09-09-24 13:54:28.webm](https://github.com/user-attachments/assets/60bb075d-7b8a-49fe-bf2c-122aec0a2007)

**Comment by PalumboN** [comment]
Esto parece ser problema de cómo se actualiza el diagrama en el frontend, que es por ID de referencia. El ID de la referencia solo tiene los ids de los objetos, pero no "el nombre de la referencia".

Acá se desincroniza porque los objetos se siguen conociendo pero es "el nombre de la referencia" (o sea, el índice) el que cambia.

**Comment by PalumboN** [comment]
Gracias @julian-berbel ! Moví el issue a este repo para darle seguimiento 🚀

**Comment by fdodino** [comment]
ahí estuve arreglando el issue para saber qué nodos cambiaron @julian-berbel 

![fix-remove](https://github.com/user-attachments/assets/f5968fef-d0a5-4904-8e23-3f382d715c6e)

calculo que la semana que viene o a lo sumo la otra hacemos un nuevo release
